# secrets.toml

# Add your API keys and other secrets here
[default]
huggingface_token = "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"


# Model details
[models]
rhea_model_name = "davidkim205/Rhea-72b-v0.5"
mixtral_model_name = "mistralai/Mixtral-8x22B-Instruct-v0.1"
opencode_model_name = "m-a-p/OpenCodeInterpreter-DS-33B"

# Other configurations
[config]
max_new_tokens = 4096

